# Generated by Django 4.1 on 2022-08-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trakoneshs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id1", models.IntegerField()),
                ("code", models.IntegerField()),
                ("id2", models.IntegerField()),
                ("cellphone", models.IntegerField()),
            ],
        ),
    ]
