# Generated by Django 4.1 on 2022-08-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trakoneshs",
            name="id2",
        ),
        migrations.AddField(
            model_name="trakoneshs",
            name="trx_id",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trakoneshs",
            name="cellphone",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="trakoneshs",
            name="code",
            field=models.CharField(max_length=20),
        ),
    ]
