# Generated by Django 4.1 on 2022-08-14 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_trakoneshs_id2_trakoneshs_trx_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trakoneshs",
            name="code",
        ),
    ]
