# Generated by Django 4.1 on 2022-08-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_trakoneshs_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="trakoneshs",
            name="code",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
